networks:
  devicePurcahsedNet:
    external: true

services:
  frontend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://100.98.57.25:4000}
    container_name: purchase_dashboard_frontend
    restart: always
    ports:
      - "3001:80"
    networks:
      - devicePurcahsedNet
