networks:
  devicePurcahsedNet:
    external: true

services:
  frontend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:4000}
    container_name: purchase_dashboard_frontend
    restart: always
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    networks:
      - devicePurcahsedNet
