networks:
  devicePurcahsedNet:
    external: true

services:
  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: purchase_dashboard_backend
    restart: always
    ports:
      - "${BACKEND_PORT:-4000}:4000"
    volumes:
      - backend_storage:/app/storage
    networks:
      - devicePurcahsedNet

volumes:
  backend_storage:
